# Generated by Django 5.2.17 on 2026-09-16 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4) for this user.', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Primary email address used for authentication and communications.', max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='last name')),
                ('phone', models.CharField(blank=True, default='', help_text='Contact phone number.', max_length=20, verbose_name='phone number')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Superadmin')], db_index=True, default='CUSTOMER', help_text='Role assigned to the user within Cartify platform.', max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether user email has been verified.', verbose_name='verified')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the account was registered.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the account was last modified.', verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'cartify_users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='user_email_idx'), models.Index(fields=['role'], name='user_role_idx'), models.Index(fields=['created_at'], name='user_created_idx')],
            },
        ),
    ]
